name: Slackbot on release

on:
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    name: Announce release on Slack
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # Dogfooding - announce or own release
      - name: Announce release on Slack
        uses: ./
        with:
          slack_webhook_url: ${{ secrets.RELEASE_SLACK_WEBHOOK_URL }}
